# Generated by Django 5.1.4 on 2025-04-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cart_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
