# Generated by Django 5.1.4 on 2025-02-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_account_balance_profile_cooperative_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adashe_cycle',
            field=models.CharField(blank=True, help_text='Current Adashe savings cycle', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='expected_payout',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_contribution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_payout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_adashe_contributions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
