# Generated by Django 5.1.4 on 2025-02-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_adashe_cycle_profile_expected_payout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_url',
            field=models.SlugField(blank=True, help_text='Optional custom URL for your profile', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('investor', 'Investor'), ('cooperative_member', 'Cooperative Member'), ('business_owner', 'Business Owner'), ('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('skilled_professional', 'Skilled Professional')], default='cooperative_member', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='account.skill'),
        ),
    ]
