# Generated by Django 5.1.4 on 2025-04-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
