# Generated by Django 5.1.4 on 2025-02-27 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='listing_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('bulk', 'Bulk Purchase'), ('skill', 'Skill'), ('wholesale', 'Wholesale')], default='normal', max_length=20),
        ),
        migrations.CreateModel(
            name='BulkContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contributed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BulkPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deadline', models.DateTimeField()),
                ('contributors', models.ManyToManyField(blank=True, through='marketplace.BulkContribution', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_purchase', to='marketplace.product')),
            ],
        ),
        migrations.AddField(
            model_name='bulkcontribution',
            name='bulk_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.bulkpurchase'),
        ),
    ]
