# Generated by Django 5.1.4 on 2025-02-11 21:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adashe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='is_missed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savingspool',
            name='members',
            field=models.ManyToManyField(related_name='joined_pools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='savingspool',
            name='contribution_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='savingspool',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_pools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='savingspool',
            name='payout_order',
        ),
        migrations.AddField(
            model_name='savingspool',
            name='payout_order',
            field=models.ManyToManyField(blank=True, related_name='payout_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
