# Generated by Django 5.1.4 on 2025-02-12 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adashe', '0002_contribution_is_missed_savingspool_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingspool',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_pools', to=settings.AUTH_USER_MODEL),
        ),
    ]
