# Generated by Django 5.1.4 on 2025-02-14 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adashe', '0003_alter_savingspool_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingspool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
